module.exports = {
  projects: [
    '<rootDir>/apps/wlodzimierz',
    '<rootDir>/libs/core/home',
    '<rootDir>/libs/core/docs',
    '<rootDir>/libs/app/users',
    '<rootDir>/libs/core/statuses',
    '<rootDir>/libs/app/app-chat',
    '<rootDir>/libs/shared/storage',
    '<rootDir>/libs/ngrx/ngrx-router',
    '<rootDir>/libs/ngrx/ngrx-error',
    '<rootDir>/libs/shared/notifications',
    '<rootDir>/libs/app/conversations',
    '<rootDir>/libs/app/conversation-messages',
    '<rootDir>/libs/app/contacts',
    '<rootDir>/libs/shared/date',
    '<rootDir>/libs/core/settings',
    '<rootDir>/libs/app/users-security',
  ],
};
