version: "3.8"

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: wlodzimierz-mssql
    ports:
      - "1433:1433"
    volumes:
      - ./.volumes/mssql:/var/opt/mssql
    networks:
      - default
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "BufKfVgDMpm9m4ZXHXpGavTAm5B"
      MSSQL_PID: "Developer"

  redis:
    image: redis:6.0.9
    container_name: wlodzimierz-redis
    ports:
      - "6379:6379"
    volumes:
      - ./.volumes/redis-data:/var/lib/redis
      - ./.volumes/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - default
    restart: unless-stopped
    environment:
      REDIS_REPLICATION_MODE: "master"

networks:
  default:
    driver: bridge
