name: .NET 5 - Deployment in Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src

    steps:
    - uses: actions/checkout@v3
    - name: Pull - Docker Compose 
      run: docker-compose -f docker-compose.dev.yml pull
      working-directory: ${{env.working-directory}}
    - name: Building & Deploy - Docker Compose 
      run: docker-compose -f docker-compose.dev.yml up --build -d
      working-directory: ${{env.working-directory}}
