name: .NET 5 - Classic build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dotnet ef
      run: dotnet tool install --global dotnet-ef
    - name: Restore dependencies
      run: dotnet restore src/WLODZIMIERZ.sln
    - name: Build with dotnet
      run: dotnet build src/WLODZIMIERZ.sln --configuration Release --no-restore
